import type { LifeOsState } from "./life-os.types";

export const settingsId = "default";

export const defaultState: LifeOsState = {
  categories: [
    {
      id: "cat-kacha-bajar",
      name: "Kacha Bajar",
      type: "monthly",
      monthlyLimit: 12000,
      weeklyLimit: 3000,
      dailyLimit: 450,
      color: "teal",
      isActive: true,
    },
    {
      id: "cat-modi-bajar",
      name: "Modi Bajar",
      type: "monthly",
      monthlyLimit: 9000,
      weeklyLimit: 2200,
      dailyLimit: 350,
      color: "amber",
      isActive: true,
    },
    {
      id: "cat-personal",
      name: "Personal Cost",
      type: "monthly",
      monthlyLimit: 6000,
      weeklyLimit: 1500,
      dailyLimit: 250,
      color: "indigo",
      isActive: true,
    },
    {
      id: "cat-baby",
      name: "Baby Cost",
      type: "monthly",
      monthlyLimit: 8000,
      weeklyLimit: 2000,
      dailyLimit: 300,
      color: "rose",
      isActive: true,
    },
  ],
  expenses: [
    {
      id: "expense-1",
      date: "2026-08-05",
      itemName: "Vegetables and fish",
      category: "Kacha Bajar",
      amount: 780,
      quantity: 1,
      unit: "bag",
      paymentMethod: "Cash",
      sourceType: "manual",
    },
    {
      id: "expense-2",
      date: "2026-08-05",
      itemName: "Rice and oil",
      category: "Modi Bajar",
      amount: 1420,
      quantity: 1,
      unit: "set",
      paymentMethod: "Cash",
      sourceType: "text",
    },
    {
      id: "expense-3",
      date: "2026-08-05",
      itemName: "Baby wipes",
      category: "Baby Cost",
      amount: 520,
      quantity: 2,
      unit: "pack",
      paymentMethod: "Card",
      sourceType: "manual",
    },
    {
      id: "expense-4",
      date: "2026-08-04",
      itemName: "Mobile data",
      category: "Personal Cost",
      amount: 399,
      quantity: 1,
      unit: "month",
      paymentMethod: "Mobile banking",
      sourceType: "recurring",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Morning planning",
      category: "Personal",
      priority: "high",
      plannedStart: "07:30",
      plannedEnd: "07:50",
      order: 1,
      actualMinutes: 20,
      status: "completed",
      repeatRule: "daily",
      alertEnabled: true,
      alertOffsetMinutes: 5,
      reminderAt: "07:25",
    },
    {
      id: "task-2",
      title: "Focused work block",
      category: "Work",
      priority: "high",
      plannedStart: "10:00",
      plannedEnd: "12:00",
      order: 2,
      actualMinutes: 75,
      status: "active",
      repeatRule: "daily",
      alertEnabled: true,
      alertOffsetMinutes: 10,
      reminderAt: "09:50",
    },
    {
      id: "task-3",
      title: "Bajar list review",
      category: "Home",
      priority: "medium",
      plannedStart: "17:30",
      plannedEnd: "18:00",
      order: 3,
      status: "pending",
      repeatRule: "daily",
      alertEnabled: true,
      alertOffsetMinutes: 15,
      reminderAt: "17:15",
    },
    {
      id: "task-4",
      title: "Family time",
      category: "Family",
      priority: "high",
      plannedStart: "20:30",
      plannedEnd: "21:30",
      order: 4,
      status: "pending",
      repeatRule: "daily",
      alertEnabled: false,
      alertOffsetMinutes: 0,
    },
  ],
  timerSessions: [
    {
      id: "timer-1",
      title: "Focused work block",
      category: "Work",
      durationSeconds: 4500,
      mode: "focus",
      createdAt: "2026-08-05T12:00:00.000Z",
    },
  ],
  notes: [
    {
      id: "note-1",
      title: "Bajar idea",
      body: "Keep a reusable shopping list and convert purchased items into expenses.",
      tags: ["budget", "bajar"],
      createdAt: "2026-08-05T08:00:00.000Z",
      updatedAt: "2026-08-05T08:00:00.000Z",
    },
    {
      id: "note-2",
      title: "Routine improvement",
      body: "Add a night review reminder after all daily tasks are done.",
      tags: ["routine"],
      createdAt: "2026-08-05T09:00:00.000Z",
      updatedAt: "2026-08-05T09:00:00.000Z",
    },
  ],
  settings: {
    profileName: "Md Arefine Ahamed Joy",
    profileEmail: "mdarefine05@gmail.com",
    profilePhone: "+880 1XXX XXXXXX",
    profileLocation: "Dhaka, Bangladesh",
    profileRole: "Personal Life OS owner",
    profileBio: "Managing budget, routine, notes, and daily life data from one local workspace.",
    profileImage: "",
    currency: "BDT",
    notificationEnabled: false,
    quietHoursStart: "22:30",
    quietHoursEnd: "06:30",
    aiProvider: "off",
  },
};
